export const dictionary = {
    "uk": {
      "mapTitle": "Видатки на відбудову України",
      "budgetType": {
        "state": "державний",
        "local": "місцеві",
        "partners": "партнери"
      },
      "spending": "Видатки",
      "monthTotal": "Усього за місяць",
      "topPayers": "Найбільші замовники",
      "topReceipts": "Найбільші отримувачі",
      "spendsType": "Тип видатків",
      "spendsPeriond": "Видатки за період",

      "planned-total": "Заплановано використати",
      "total-spent": "Усього використано",
      "state-spent": "Державний бюджет",
      "local-spent": "Місцевий бюджет",
      "partners-spent": "Кошти партнерів",
      "filters": "Фільтри",
      "f-budget": "Бюджет",
      "f-objcat": "Категорія об'єкту",
      "f-budgprg": "Бюджетна програма",
      "f-payerid": "ЄДРПОУ Платника",
      "f-receiptid": "ЄДРПОУ Отримувача",
      "f-year": "Рік",
      "f-reset": "Скинути",
      "f-resetall": "Скинути всі фільтри",

      "type": "Тип",
      "amount": "Грн",
      "lamount": "грн",
      "code": "UA",
      "bln": "млрд",
      "mln": "млн",
      "k": "тис",

      "lregion": "область",
      "region": "Область",
      "district": "Район",
      "ldistrict": "район",
      "terhromada": "Тергромада",
      "lterhromada": "тергромада",
      "settlement": "Населений Пункт",
      "lsettlement": "населений пункт",
      "address": "Адреса",
      "financed": "Профінансовано",

      "payer": "Замовник",
      "receipt": "Отримувач",
      "payerId": "Замовник (ЄДРПОУ)",
      "receiptId": "Отримувач (ЄДРПОУ)",
      "program": "Програма",
      "type": "Тип",
      "uah": "грн",

      "t-program": "Програма",
      "t-objects-count": "Кількість об'єктів",
      "t-financed": "Профінансовано, грн",
      "t-address": "Адреса",
      "t-type": "Тип об'єкту",
      "t-plan": "Заплановано використати, грн",
      "t-spends": "Фактичні витрати, грн",
      "t-percentage": "Відсоток, %",
      "h-table-title": "Програми, з яких фінансуються видатки: ",
      "note": "Примітка",

      "all": "Всі",
      "monthNames": {
        0: "Січ",
        1: "Лют",
        2: "Бер",
        3: "Кві",
        4: "Тра",
        5: "Чер",
        6: "Лип",
        7: "Сер",
        8: "Вер",
        9: "Жов",
        10: "Лис",
        11: "Гру"
      }
    },
    "en": {
      "mapTitle": "",
      "budgetType": {
        "state": "state",
        "local": "local",
        "partners": "international partners"
      },
      "spending": "Actual",
      "payer": "Payer",
      "receipt": "Recipient",
      "monthTotal": "Total per month",
      "topPayers": "Top payers, UAH",
      "topReceipts": "Top recipients, UAH",
      "spendsType": "Type",
      "spendsPeriond": "Period",

      "planned-total": "Plan",
      "state-spent": "State budget",
      "local-spent": "Local budget",
      "partners-spent": "International partners",
      "filters": "Filters",
      "f-budget": "Budget",
      "f-objcat": "Object category",
      "f-budgprg": "Budget program",
      "f-payerid": "Payer ID",
      "f-receiptid": "Receipt ID",
      "f-year": "Year",
      "f-reset": "Reset",
      "f-resetall": "Reset all",

      "amount": "UAH",
      "lamount": "UAH",
      "code": "EN",
      "bln": "bln",
      "mln": "mln",
      "k": "k",

      "lregion": "oblast",
      "region": "Oblast",
      "district": "District",
      "ldistrict": "district",
      "terhromada": "Hromada",
      "lterhromada": "hromada",
      "settlement": "Settlement",
      "lsettlement": "settlement",
      "address": "Address",
      "financed": "Actual",

      "payer": "Payer Name",
      "receipt": "Recipient",
      "payerId": "Payer ID",
      "receiptId": "Receipt ID",
      "program": "Program",
      "type": "Type",
      "uah": "UAH",

      "t-program": "Program",
      "t-objects-count": "Number of objects",
      "t-financed": "UAH",
      "t-address": "Address",
      "t-type": "Type",
      "t-plan": "Plan",
      "t-spends": "UAH",
      "t-percentage": "%",
      "h-table-title": "Programs from which funding is provided:",
      "total-spent": "Actual",
      "note": "Note",

      "all": "All",
      "monthNames": {
        0: "Jan",
        1: "Feb",
        2: "Mar",
        3: "Apr",
        4: "May",
        5: "Jun",
        6: "Jul",
        7: "Aug",
        8: "Sep",
        9: "Oct",
        10: "Nov",
        11: "Dec",
      }
  }
};